[workspace]
resolver = "3"
members = [
    "crates/kernel",
    "crates/arch-aarch64",
    "crates/drivers",
    "crates/boot-protocol",
    "crates/user-abi",
    "boards/qemu-virt",
    "boards/rpi5",
    "crates/fdt",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace.dependencies]
kernel = { package = "haechix-kernel", path = "crates/kernel" }
arch-aarch64 = { package = "haechix-arch-aarch64", path = "crates/arch-aarch64" }
drivers = { package = "haechix-drivers", path = "crates/drivers" }
boot-protocol = { package = "haechix-boot-protocol", path = "crates/boot-protocol" }
user-abi = { package = "haechix-user-abi", path = "crates/user-abi" }
fdt = { package = "haechix-fdt", path = "crates/fdt" }
